name: base
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip=22.1.2
  - pip:
      - sqlalchemy==1.4.41
      - PyMySQL==1.0.2
      - pandas==1.5.0
      - numpy==1.23.3
      - openpyxl==3.0.10
      - icecream==2.1.3
      - dask==2022.10.2
      - distributed==2022.10.2
      - python-dateutil==2.8.2
      - async_lru==1.0.3
      - loguru
      - psutil==5.9.3
      - qtlib==0.0.3
      - scipy==1.9.3
      - statsmodels==0.13.5
      - pytest-asyncio==0.20.3
      - asgiref==3.5.2
      - chinese-calendar==1.8.0

